// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Character, CharacterData } from "./tables/Character.sol";
import { Player, PlayerData } from "./tables/Player.sol";
import { PlayerPrivateState } from "./tables/PlayerPrivateState.sol";
import { VerifierContracts, VerifierContractsData } from "./tables/VerifierContracts.sol";
